-- MySQL Script generated by MySQL Workbench
-- Wed Oct 13 15:21:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`anuncios` (
  `codigo` VARCHAR(255) NOT NULL,
  `data_anuncio` DATE NULL DEFAULT NULL,
  `num_vendas` INT NULL DEFAULT NULL,
  `preco` DECIMAL(19,2) NULL DEFAULT NULL,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`vendedores` (
  `codigo` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `situacao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`enderecos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `logradouro` VARCHAR(255) NULL DEFAULT NULL,
  `numero` INT NOT NULL,
  `uf` VARCHAR(255) NULL DEFAULT NULL,
  `vendedor_codigo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKli0x5t51m9692184k84arbrrp` (`vendedor_codigo` ASC) VISIBLE,
  CONSTRAINT `FKli0x5t51m9692184k84arbrrp`
    FOREIGN KEY (`vendedor_codigo`)
    REFERENCES `project`.`vendedores` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`pedidos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`pedidos_anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`pedidos_anuncios` (
  `Pedido_id` BIGINT NOT NULL,
  `anuncios_codigo` VARCHAR(255) NOT NULL,
  INDEX `FKc7wfw7g8lmob60wv544aymr24` (`anuncios_codigo` ASC) VISIBLE,
  INDEX `FKbo1dsnh1yj83f0lvx0jl9ot5o` (`Pedido_id` ASC) VISIBLE,
  CONSTRAINT `FKbo1dsnh1yj83f0lvx0jl9ot5o`
    FOREIGN KEY (`Pedido_id`)
    REFERENCES `project`.`pedidos` (`id`),
  CONSTRAINT `FKc7wfw7g8lmob60wv544aymr24`
    FOREIGN KEY (`anuncios_codigo`)
    REFERENCES `project`.`anuncios` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`vendas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL DEFAULT NULL,
  `formaPagamento` VARCHAR(255) NULL DEFAULT NULL,
  `valorTotal` DECIMAL(19,2) NULL DEFAULT NULL,
  `vendedor_codigo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKhhljn7te4l2b5xyesvi0a7cnn` (`vendedor_codigo` ASC) VISIBLE,
  CONSTRAINT `FKhhljn7te4l2b5xyesvi0a7cnn`
    FOREIGN KEY (`vendedor_codigo`)
    REFERENCES `project`.`vendedores` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
