-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.anuncios
(
    codigo character varying(20) NOT NULL,
    titulo character varying(1000) NOT NULL,
    vendedor_codigo character varying(10) NOT NULL,
    preco numeric NOT NULL,
    data_anuncio date,
    num_vendas integer,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public.endereco
(
    id bigint NOT NULL,
    cep character varying(255),
    cidade character varying(255),
    complemento character varying(255),
    logradouro character varying(255),
    numero integer NOT NULL,
    uf character varying(255),
    vendedor_codigo character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.venda
(
    id bigint NOT NULL,
    data date,
    formapagamento character varying(255),
    valortotal numeric(19, 2),
    vendedor_codigo character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vendedores
(
    codigo character varying(10) NOT NULL,
    cpf character varying(14) NOT NULL,
    nome character varying(255) NOT NULL,
    PRIMARY KEY (codigo)
);

ALTER TABLE IF EXISTS public.anuncios
    ADD FOREIGN KEY (vendedor_codigo)
    REFERENCES public.vendedores (codigo)
    NOT VALID;


ALTER TABLE IF EXISTS public.endereco
    ADD FOREIGN KEY (vendedor_codigo)
    REFERENCES public.vendedores (codigo)
    NOT VALID;


ALTER TABLE IF EXISTS public.venda
    ADD FOREIGN KEY (vendedor_codigo)
    REFERENCES public.vendedores (codigo)
    NOT VALID;

END;